# site
title: ".Code()"
description: "Coding for fun."

paginate: 5

# social
email: "rollins.joseph@gmail.com"
github_username: "fortruce"

url: "http://localhost:4000"

defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"