# site
title: ".Code()"
tagline: "Programming for fun."

paginate: 5

# social
email: "rollins.joseph@gmail.com"
github_username: "fortruce"

url: "http://josephmr.com"

highlighter: pygments

defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"